[package]
name = "orders-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "postgres", "chrono", "macros"] }
reqwest = { version = "0.13", default-features = false, features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
mimalloc = { version = "0.1", default-features = false }
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
bytes = "1.12.1"

[profile.release]
lto = "thin"
codegen-units = 16
strip = true
